spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8
server:
  port: 8083
logging:
  level:
    root: error
    org.springframework: error
    org.mybatis: debug
    com.choodsire666.litemall.admin: debug
    com.choodsire666.litemall: error
knife4j:
  production: false